FROM node:20

WORKDIR /app

COPY package*.json  ./

RUN apk add --no-cache\
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    udev
RUN npm install --no-cache

COPY . .
EXPOSE 3001
CMD [ "npm","run","dev" ]